[project]
name = "autonomous-rc-car"
version = "0.1.0"
description = "Self driving RC car"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "adafruit-blinka>=8.69.0",
    "adafruit-circuitpython-pca9685>=3.4.20",
    "pillow>=12.1.0",
    "tornado>=6.5.4",
]

[project.scripts]
drive = "manage:main"
